name: messenger_clone_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.12.0
  dartz: ^0.10.1
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  fpdart: ^1.1.0
  go_router: ^12.0.0
  hooks_riverpod: ^2.4.4
  intl: ^0.18.1
  riverpod: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: klavika
      fonts:
        - asset: assets\fonts\klavika-bold-italic.otf
          weight: 100
        - asset: assets\fonts\klavika-bold.otf
          weight: 200
        - asset: assets\fonts\klavika-light-italic.otf
          weight: 300
        - asset: assets\fonts\klavika-light.otf
          weight: 400
        - asset: assets\fonts\klavika-medium-italic.otf
          weight: 500
        - asset: assets\fonts\klavika-medium.otf
          weight: 600
        - asset: assets\fonts\klavika-regular-italic.otf
          weight: 700
          
  assets:
      - assets\images\Facebook_Logo_Primary.png
      - assets\images\Facebook_Logo_Secondary.png
      - assets\images\download.jpg
      - assets\images\images.jpg
      - assets\images\IMG20221027193308.jpg
      - assets\icons\facebook_reaction_icons\angry.png
      - assets\icons\facebook_reaction_icons\sad.png
      - assets\icons\facebook_reaction_icons\care.png
      - assets\icons\facebook_reaction_icons\wow.png
      - assets\icons\facebook_reaction_icons\like.png
      - assets\icons\facebook_reaction_icons\haha.png
      - assets\icons\facebook_reaction_icons\love.png
      - assets\images\CJ.jpg
      - assets\images\steve.jpg
      - assets\images\joel.jpg
      - assets\images\dingodile.jpg
      - assets\images\crash.jpg
      - assets\images\default_picture.jpg

